version: "3.8"

services:
    pgdb:
        image: postgres
        container_name: pgdb
        env_file: .env
        environment:
            POSTGRES_HOST: ${POSTGRES_HOST}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_INITDB_ARGS: "-A md5"
        ports:
            - "5433:5432"

    django:
        build: .
        container_name: django
        command: /bin/bash -c "exec invoke run-local"
        volumes:
            - .:/usr/src/app
        ports:
            - "8000:8000"
        depends_on:
            - pgdb
        env_file: .env
